name: CI pipeline

# Defines when to trigger this workflow
on:
  # When pushing commit(s) to master or adding any tag(s).
  push:
    branches: [ master ]
    tags: [ '**' ]
  # When submiting pull request to master.
  pull_request:
    branches: [ master ]
    tags: [ '**' ]
  # Every Monday, 1:00 am (UTC).
  schedule:
    - cron: '0 1 * * 1'

# Defines all jobs to be run in parallel.
jobs:
  # See https://help.github.com/en/actions/language-and-framework-guides/github-actions-for-java
  build-and-test:
    name: Build & test on JDK ${{ matrix.java }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [11, 14, 16]
    steps:
      # See https://github.com/actions/checkout
      - name: Download the repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50
      # See https://github.com/actions/setup-java
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      # See https://github.com/actions/cache
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      # See https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
      - name: Build & test with Gradle
        run: ./gradlew clean build

  # See https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action
  validate-gradle:
    name: Validate Gradle wrapper
    runs-on: ubuntu-20.04
    steps:
      # See https://github.com/actions/checkout
      - name: Download the repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50
      # See https://github.com/gradle/wrapper-validation-action
      - name: Validate gradle-wrapper.jar
        uses: gradle/wrapper-validation-action@v1.0.4

  # See https://help.github.com/en/actions/language-and-framework-guides
  validate-links:
    name: Validate links in README.md
    runs-on: ubuntu-20.04
    steps:
      # See https://github.com/actions/checkout
      - name: Download the repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 50
      # See https://github.com/actions/setup-ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.7
      # See https://github.com/actions/setup-ruby
      - name: Install awesome_bot
        run: gem install awesome_bot
      # See https://github.com/dkhamsing/awesome_bot
      - name: Validate links in Markdown
        run: awesome_bot README.md --allow-dupe --allow-redirect --allow 429 -w linkedin.com --skip-save-results
